# Generated by Django 5.0.4 on 2024-05-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
    ]
