# Generated by Django 5.0.4 on 2024-05-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_remove_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to='shopapp.product'),
            preserve_default=False,
        ),
    ]
