# Generated by Django 5.0.4 on 2024-05-11 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=7)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
